### ISSUE TITLE
Can not compile for R21

### ISSUE THREAD

**Issue by ilayshp** [NiklasRosenstein/c4d-nr-toolbox#8]
Hello
I can not compile for R21, several vendor api are missing

**Comment by NiklasRosenstein** [comment]
Hey Ilay,

what's the error you're getting? Did you check out Git submodules? I don't have access to R21 unfortnuately.

**Comment by ilayshp** [comment]
under vendor dir:
have not includes - NiklasRosenstein, craftr, davisking

sorry i did not make copies and your gitlab - 502 Bad Gateway

**Comment by ilayshp** [comment]
I tried clone git and make command _git submodule update --init --recursive_
But vendor does not work

**Comment by NiklasRosenstein** [comment]
Ah, gotcha. Sorry about that. I recently shut down GitLab. I've turned it back on for now, and I before I shut it down again I'll migrate update this repo to reference libs from GitHub.

**Comment by NiklasRosenstein** [comment]
Not sure where cpp-tinylib ended up living, I'll look into it tomorrow.

**Comment by NiklasRosenstein** [comment]
Ah seems like I didn't update `nr.mathlib` to point to [`nr.utils`](https://gitlab.niklasrosenstein.com/NiklasRosenstein/cxx/nr.utils) instead of `cpp-tinylib`.

**Comment by ilayshp** [comment]
Ok, i will skip R21. Moving to blender

**Comment by NiklasRosenstein** [comment]
Hey @ilayshp , I just uploaded an R21 build for Windows here: https://github.com/NiklasRosenstein/c4d-nr-toolbox/releases/tag/v1.1.1
